/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : string,
  'itemId' : string,
  'participants' : Array<Principal>,
  'messages' : Array<Message>,
}
export type ExternalBlob = Uint8Array;
export interface FeedbackEntry {
  'id' : bigint,
  'createdAt' : Time,
  'user' : Principal,
  'message' : string,
  'rating' : bigint,
}
export interface FeedbackEntryWithReadStatus {
  'id' : bigint,
  'createdAt' : Time,
  'user' : Principal,
  'isRead' : boolean,
  'message' : string,
  'rating' : bigint,
}
export interface Item {
  'id' : string,
  'status' : Status,
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'itemType' : ItemType,
  'category' : string,
  'photo' : [] | [ExternalBlob],
  'dateTime' : string,
  'location' : string,
}
export type ItemType = { 'found' : null } |
  { 'lost' : null };
export interface Message {
  'id' : string,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface PushSubscription {
  'endpoint' : string,
  'auth' : string,
  'p256dh' : string,
}
export type Status = { 'missing' : null } |
  { 'claimed' : null } |
  { 'returned' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConversation' : ActorMethod<[string], string>,
  'createItem' : ActorMethod<
    [ItemType, string, string, string, string, string, [] | [ExternalBlob]],
    string
  >,
  'getAllFeedback' : ActorMethod<[], Array<FeedbackEntryWithReadStatus>>,
  'getCallerFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string], [] | [Conversation]>,
  'getItem' : ActorMethod<[string], [] | [Item]>,
  'getRecipientPushSubscriptions' : ActorMethod<
    [Principal],
    Array<PushSubscription>
  >,
  'getRegisteredUsersCount' : ActorMethod<[], bigint>,
  'getUnreadFeedbackCount' : ActorMethod<[], bigint>,
  'getUserConversations' : ActorMethod<[Principal], Array<Conversation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllFeedbackAsRead' : ActorMethod<[], undefined>,
  'markFeedbackAsRead' : ActorMethod<[bigint], undefined>,
  'registerPushSubscription' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchItems' : ActorMethod<
    [string, [] | [string], [] | [ItemType]],
    Array<Item>
  >,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'submitFeedback' : ActorMethod<[string, bigint], undefined>,
  'unregisterPushSubscription' : ActorMethod<[string], undefined>,
  'updateItemStatus' : ActorMethod<[string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];