/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const FeedbackEntry = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Conversation = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'messages' : IDL.Vec(Message),
});
export const Status = IDL.Variant({
  'missing' : IDL.Null,
  'claimed' : IDL.Null,
  'returned' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'itemType' : ItemType,
  'category' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'dateTime' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createItem' : IDL.Func(
      [
        ItemType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getCallerFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Text], [IDL.Opt(Conversation)], ['query']),
  'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
  'getUserConversations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchItems' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ItemType)],
      [IDL.Vec(Item)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitFeedback' : IDL.Func([IDL.Text], [], []),
  'updateItemStatus' : IDL.Func([IDL.Text, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const FeedbackEntry = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'messages' : IDL.Vec(Message),
  });
  const Status = IDL.Variant({
    'missing' : IDL.Null,
    'claimed' : IDL.Null,
    'returned' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'itemType' : ItemType,
    'category' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'dateTime' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createItem' : IDL.Func(
        [
          ItemType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getCallerFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
    'getUserConversations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchItems' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ItemType)],
        [IDL.Vec(Item)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitFeedback' : IDL.Func([IDL.Text], [], []),
    'updateItemStatus' : IDL.Func([IDL.Text, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };